name: Publish Github-Releases

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      os:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  github-releases:
    name: ${{ inputs.artifact_name }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_artifact
        with:
          name: ${{ inputs.artifact_name }}

      - name: Download artifacts
        if: steps.check_artifact.outputs.exists == 'true'
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ./artifact

      - name: Get file
        if: steps.check_artifact.outputs.exists == 'true'
        id: get_file_name
        shell: bash
        working-directory: ./artifact
        run: |
          ls -R
          echo "file_name=$(ls | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload artifact to release
        if: steps.check_artifact.outputs.exists == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/${{ steps.get_file_name.outputs.file_name }}
          tag: ${{ inputs.tag }}
          overwrite: true